### ISSUE TITLE
Unhandled exception when deleting a map subfolder

### ISSUE THREAD

**Issue by PWase** [galister/dcs-kbm#1]
![image](https://user-images.githubusercontent.com/77615370/108389027-88323600-720f-11eb-9f3a-d9d9be902eb4.png)

![image](https://user-images.githubusercontent.com/77615370/108389006-823c5500-720f-11eb-827c-6c38dfe817d6.png)

**Comment by galister** [comment]
Confirmed fixed in 1.0.2
